freeze("$(PORT_DIR)/modules")
include("$(MPY_DIR)/extmod/asyncio")

# Requirements commented out for clean bootstrap build (no git submodules)
# require("bundle-networking")
# require("aioespnow")
# require("dht")
# require("ds18x20")
# require("neopixel")
# require("onewire")
# require("umqtt.robust")
# require("umqtt.simple")
# require("upysh")
